"""rafts_regn_params_gpkg.py

Unified script for extracting regionalized parameters and writing them as
new attribute tables into a standalone SQLite database and a Master GeoPackage.

- Unsupervised (Clustering): Reads pre-compiled receiver_params generated by rafts_pair_donors.py.
- Supervised (Regression): Horizontally merges individual parameter predictions
  from rafts_pred_algo.py and applies optional crosswalking.

The tables are written with 'divide_id' set as the formal index and include
the algorithm string in the table name (e.g., formulation_algo). The script
filters algorithms using wildcard matching from 'algo_select'.

When sub-regions are configured (see rafts_algo.regions), this script stitches them back
together: it reads each region's own per-region output tree, tags every row with region_id
and model_scope, and writes the UNION of all regions to the single, shared SQLite/GeoPackage
destination exactly once per table -- never once per region, since
raftsutil.update_database's overwrite path would let a later region's write silently replace
an earlier region's rows.

Usage:
    >>> python rafts_regn_params_gpkg.py "/path/to/pred_config.yaml"

Changelog / Contributions:
2026-09-18 Refactored to integrate Pydantic PredConfig schema validation.
2026-10-03 feat: Stitch per-region output (see rafts_algo.regions) into the shared GPKG/SQLite
           destination; CONUS-wide (no `regions:` config) behavior is unchanged.
"""

import argparse
import pandas as pd
from pathlib import Path
import logging
import sys
import shutil
import fnmatch

import rafts_algo.utils as raftsutil
import rafts_algo.regions as raftsregions
import rafts_prep.proc_eval_metrics as pem
from rafts_algo.schemas.pydantic_schemas import PredConfig

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Write regionalized parameters to a standalone GeoPackage.')
    parser.add_argument('path_pred_config', type=str, help='Path to the prediction YAML config.')
    parser.add_argument('--region', type=str, default=None,
                        help="Restrict this run to a single configured sub-region's region_id. "
                             "Omit to stitch together every region the pred config's `regions:` "
                             "block resolves to (or run once, unregioned, if `regions:` isn't set).")
    args = parser.parse_args()

    path_pred_config = Path(args.path_pred_config).expanduser()

    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logging.info(f"Running rafts_regn_params_gpkg.py using {path_pred_config.name}")

    # --- Pydantic Validation ---
    validated_pred_cfg = raftsutil.load_validated_config(path_pred_config, PredConfig)

    path_attr_config = raftsutil.build_cfig_path(path_pred_config, validated_pred_cfg.name_attr_config)
    attr_cfig = raftsutil.AttrConfigAndVars(path_attr_config)
    attr_cfig._read_attr_config()

    # Load Algo Config to determine if we are doing Supervised or Unsupervised writing
    path_algo_config = raftsutil.build_cfig_path(path_pred_config, validated_pred_cfg.name_algo_config)
    algo_cfig = raftsutil.AlgoConfigParser(path_algo_config)
    algo_cfig._read_algo_config()
    task_type = algo_cfig.algo_cfg_unc_dict["algo_cfg_dict"].get("task_type", "regression")

    dir_base = attr_cfig.attrs_cfg_dict.get('dir_base')
    dir_std_base = attr_cfig.attrs_cfg_dict.get('dir_std_base')
    dir_db_attrs = attr_cfig.attrs_cfg_dict.get('dir_db_attrs')
    datasets = attr_cfig.attrs_cfg_dict.get('datasets')
    home_dir = attr_cfig.attrs_cfg_dict.get('home_dir')

    context = {
        'dir_base': str(dir_base),
        'dir_std_base': str(dir_std_base),
        'dir_db_attrs': str(dir_db_attrs),
        'home_dir': str(home_dir),
    }

    # Fetch validated configuration variables directly from Pydantic
    overwrite_sql = validated_pred_cfg.overwrite_sql
    base_algos = validated_pred_cfg.algo_type or []
    resp_vars = validated_pred_cfg.algo_response_vars or []
    pred_gpkg_id_col = validated_pred_cfg.pred_gpkg_id_col or 'featureID'
    crosswalk_target_col = validated_pred_cfg.crosswalk_target_col

    algo_select = validated_pred_cfg.algo_select or []
    if isinstance(algo_select, str):
        algo_select = [algo_select]

    regions_cfg = validated_pred_cfg.regions  # None unless this config sets a `regions:` block
    region_loop = raftsregions.resolve_region_loop(regions_cfg, args.region, context=context)
    region_scheme = regions_cfg.scheme if regions_cfg else None

    # Locate the Prep Config to extract formulation ID
    try:
        name_prep_config = [x for x in attr_cfig.attr_config.get('file_io') if 'name_prep_config' in x][0]['name_prep_config']
        path_prep_config = raftsutil.build_cfig_path(path_pred_config, name_prep_config)
        col_schema_df = pem.read_schm_ls_of_dict(path_prep_config)
        formulation_id = pem.std_form_id(col_schema_df)
        logging.info(f"Resolved base formulation name: {formulation_id}")
    except Exception as e:
        logging.error(f"Failed to resolve prep config or formulation ID: {e}")
        sys.exit(1)

    # The final, stitched output always lands in the shared (unregioned) destination --
    # regions are an input-reading concern below, never a second output root here.
    dirs_std_dict = raftsutil.rafts_save_algo_dir_struct(dir_base)
    dir_out = Path(dirs_std_dict.get('dir_out'))
    subdir = path_pred_config.parent.name
    dir_regionalization_sub = dir_out / "regionalization" / subdir
    dir_regionalization_sub.mkdir(parents=True, exist_ok=True)

    # Initialize Master GPKG Path
    path_hf_finl_gpkg_raw = validated_pred_cfg.path_hf_finl_gpkg
    if not path_hf_finl_gpkg_raw:
        logging.error("No 'path_hf_finl_gpkg' found in prediction config.")
        sys.exit(1)

    path_hf_finl_gpkg = Path(raftsutil.resolve_fstrings(path_hf_finl_gpkg_raw, context))
    if not path_hf_finl_gpkg.exists():
        logging.error(f"Source Master GPKG does not exist: {path_hf_finl_gpkg}")
        sys.exit(1)

    # Ensure local Master GPKG copy exists
    dest_master_path = dir_regionalization_sub / path_hf_finl_gpkg.name.replace('.gpkg','_regn.gpkg')
    if not dest_master_path.exists():
        logging.info(f"Initializing local Master GPKG by copying {path_hf_finl_gpkg.name} to {dest_master_path.parent}")
        shutil.copy2(path_hf_finl_gpkg, dest_master_path)

    # =========================================================================
    # Process Datasets and Write Tables
    # =========================================================================
    for ds in datasets:
        logging.info(f"Processing {ds} dataset. Task Type: {task_type}")

        if task_type == 'clustering':
            # -----------------------------------------------------------------
            # UNSUPERVISED FLOW: read pre-compiled donor-receiver tables, one region at a
            # time, accumulating each algo's rows across all regions before writing (see
            # module docstring for why update_database must be called once per table, not
            # once per region).
            # -----------------------------------------------------------------
            for resp_var in resp_vars:
                accumulated_by_algo = {}  # algo -> list of (df_params, is_mapped)

                for region_id, region_spec in region_loop:
                    dirs_std_dict_r = raftsutil.rafts_save_algo_dir_struct(dir_base, region=region_id, scheme=region_scheme)
                    dir_out_r = Path(dirs_std_dict_r.get('dir_out'))
                    dir_out_alg_ds_r = Path(dirs_std_dict_r.get('dir_out_alg_base')) / ds
                    dir_ds_regn_r = dir_out_r / "regionalization" / ds

                    dynamic_algos = raftsutil.discover_dynamic_algos(
                        search_dir=dir_out_alg_ds_r,
                        base_algos=base_algos,
                        metric=resp_var,
                        dataset_id=ds,
                        file_prefix="algo_",
                        file_extension=".joblib"
                    )

                    for algo in dynamic_algos:
                        # --- APPLY ALGO_SELECT FILTER ---
                        if algo_select:
                            matched = any(fnmatch.fnmatch(algo, pattern) for pattern in algo_select)
                            if not matched:
                                logging.info(f"Algorithm '{algo}' skipped (does not match 'algo_select' patterns).")
                                continue

                        param_file_mapped = dir_ds_regn_r / f"receiver_params_mapped_{algo}_{resp_var}__{ds}.parquet"
                        param_file_std = dir_ds_regn_r / f"receiver_params_{algo}_{resp_var}__{ds}.csv"

                        if param_file_mapped.exists():
                            param_file = param_file_mapped
                        elif param_file_std.exists():
                            param_file = param_file_std
                        else:
                            logging.error(f"No parameter files found for {algo} and {resp_var} in {dir_ds_regn_r}")
                            continue

                        logging.info(f"Loading regionalized parameters from {param_file.name}" +
                                     (f" (region '{region_id}')" if region_id else ""))
                        if param_file.suffix == '.parquet':
                            df_params = pd.read_parquet(param_file)
                        else:
                            df_params = pd.read_csv(param_file)

                        df_params['region_id'] = region_id if region_id else 'CONUS'
                        df_params['model_scope'] = raftsregions.read_model_scope_sidecar(
                            dir_out_alg_ds_r, default=('conus' if region_id is None else 'region'))

                        is_mapped = "mapped" in param_file.name
                        accumulated_by_algo.setdefault(algo, []).append((df_params, is_mapped))

                for algo, entries in accumulated_by_algo.items():
                    df_params_all = pd.concat([e[0] for e in entries], ignore_index=True)
                    any_mapped = any(e[1] for e in entries)

                    # Determine expected ID column based on whether the file was crosswalk-mapped
                    expected_cols = []
                    if any_mapped:
                        if crosswalk_target_col: expected_cols.append(crosswalk_target_col)
                        expected_cols.append('divide_id')

                    expected_cols.extend([pred_gpkg_id_col, 'featureID'])

                    # Remove duplicates while preserving order
                    expected_cols = list(dict.fromkeys(expected_cols))

                    # Safely identify the first matching column
                    id_col = next((col for col in expected_cols if col in df_params_all.columns), None)

                    if not id_col:
                        id_col = df_params_all.columns[0]
                        if not any_mapped:
                            logging.warning(f"Expected identifier columns {expected_cols} not found. Defaulting to first column: '{id_col}'.")

                    # Dynamically generate table and file names
                    table_name = f"{formulation_id}_{algo}"
                    path_output_sql = dir_regionalization_sub / f"compiled_regionalized_params_{algo}.sqlite"

                    # Write/Append to Local SQLite DB & Master GPKG -- once, for all regions.
                    raftsutil.update_database(path_output_sql, df_params_all, table_name, id_col, overwrite_sql)
                    raftsutil.update_database(dest_master_path, df_params_all, table_name, id_col, overwrite_sql)
                    logging.info(f"Updated hydrofabric geopackage at {dest_master_path} with table '{table_name}'")

        else:
            # -----------------------------------------------------------------
            # SUPERVISED FLOW: horizontally merge individual parameter predictions, one
            # region at a time, accumulating before writing (see unsupervised branch above
            # for why update_database must be called once per table, not once per region).
            # -----------------------------------------------------------------
            if not resp_vars:
                logging.error("No response variables defined in config to compile.")
                continue

            for algo in base_algos:
                # --- APPLY ALGO_SELECT FILTER ---
                if algo_select:
                    matched = any(fnmatch.fnmatch(algo, pattern) for pattern in algo_select)
                    if not matched:
                        logging.info(f"Algorithm '{algo}' skipped (does not match 'algo_select' patterns).")
                        continue

                logging.info(f"Compiling supervised predictions for algorithm: {algo}")
                id_col_pred = validated_pred_cfg.pred_file_comid_colname
                region_results = []  # list of (df_compiled_params, current_id_col)

                for region_id, region_spec in region_loop:
                    dirs_std_dict_r = raftsutil.rafts_save_algo_dir_struct(dir_base, region=region_id, scheme=region_scheme)
                    dir_out_r = Path(dirs_std_dict_r.get('dir_out'))
                    dir_out_alg_ds_r = Path(dirs_std_dict_r.get('dir_out_alg_base')) / ds

                    df_compiled_params = pd.DataFrame()
                    current_id_col = None

                    # Compile all parameter predictions into a single wide DataFrame
                    for resp_var in resp_vars:
                        pred_path = raftsutil.std_pred_path(dir_out=dir_out_r, algo=algo, metric=resp_var, dataset_id=ds)

                        if not pred_path.exists():
                            logging.error(f"Prediction file missing for parameter '{resp_var}': {pred_path}")
                            continue

                        df_pred = pd.read_parquet(pred_path)

                        if 'prediction' not in df_pred.columns:
                            logging.warning(f"No 'prediction' column found in {pred_path.name}. Skipping.")
                            continue

                        current_id_col = 'featureID' if 'featureID' in df_pred.columns else id_col_pred
                        df_sub = df_pred[[current_id_col, 'prediction']].rename(columns={'prediction': resp_var})

                        if df_compiled_params.empty:
                            df_compiled_params = df_sub
                        else:
                            df_compiled_params = df_compiled_params.merge(df_sub, on=current_id_col, how='outer')

                    if df_compiled_params.empty:
                        logging.warning(f"Failed to compile any parameters for algorithm {algo} in region "
                                         f"'{region_id}'. Skipping.")
                        continue

                    # OPTIONAL CROSSWALK MAPPING
                    path_crosswalk_ids_raw = validated_pred_cfg.path_crosswalk_ids
                    pred_gpkg_id_col_local = validated_pred_cfg.pred_gpkg_id_col

                    if path_crosswalk_ids_raw:
                        path_crosswalk_ids = Path(raftsutil.resolve_fstrings(path_crosswalk_ids_raw, context))
                        if path_crosswalk_ids.exists():
                            logging.info(f"Applying crosswalk mapping from {path_crosswalk_ids}")

                            df_crosswalk = pd.read_parquet(path_crosswalk_ids).astype(str) if str(path_crosswalk_ids).endswith('.parquet') else pd.read_csv(path_crosswalk_ids, dtype=str)

                            desired_id_col = raftsutil.get_crosswalk_target_col(df_crosswalk, pred_gpkg_id_col_local, crosswalk_target_col)

                            if desired_id_col:
                                df_compiled_params[current_id_col] = df_compiled_params[current_id_col].astype(str)

                                df_compiled_params = df_compiled_params.merge(
                                    df_crosswalk, left_on=current_id_col, right_on=pred_gpkg_id_col_local, how='inner'
                                )

                                cols_to_drop = [current_id_col]
                                if pred_gpkg_id_col_local in df_compiled_params.columns and pred_gpkg_id_col_local != desired_id_col:
                                    cols_to_drop.append(pred_gpkg_id_col_local)

                                df_compiled_params = df_compiled_params.drop(columns=cols_to_drop, errors='ignore')
                                new_col_order = [desired_id_col] + [c for c in df_compiled_params.columns if c != desired_id_col]
                                df_compiled_params = df_compiled_params[new_col_order]

                                current_id_col = desired_id_col
                            else:
                                logging.error(f"Crosswalk file missing the specified pred_gpkg_id_col: {pred_gpkg_id_col_local}")
                        else:
                            logging.error(f"Crosswalk file path was provided but does not exist: {path_crosswalk_ids}")

                    df_compiled_params['region_id'] = region_id if region_id else 'CONUS'
                    df_compiled_params['model_scope'] = raftsregions.read_model_scope_sidecar(
                        dir_out_alg_ds_r, default=('conus' if region_id is None else 'region'))
                    region_results.append((df_compiled_params, current_id_col))

                if not region_results:
                    logging.warning(f"Failed to compile any parameters for algorithm {algo}. Skipping database update.")
                    continue

                # Every region resolves its own current_id_col (crosswalk-mapped or not)
                # independently; they're expected to agree (same algo, same crosswalk
                # config) -- use the first region's name and let pd.concat's own column
                # alignment surface a mismatch rather than silently picking one.
                final_id_col = region_results[0][1]
                df_compiled_params_all = pd.concat([df for df, _ in region_results], ignore_index=True)

                id_col = pred_gpkg_id_col if pred_gpkg_id_col in df_compiled_params_all.columns else final_id_col
                table_name = f"{formulation_id}_{algo}"
                path_output_sql = dir_regionalization_sub / f"compiled_supervised_params_{algo}.sqlite"

                # Write/Append to Local SQLite DB & Master GPKG -- once, for all regions.
                raftsutil.update_database(path_output_sql, df_compiled_params_all, table_name, id_col, overwrite_sql)
                raftsutil.update_database(dest_master_path, df_compiled_params_all, table_name, id_col, overwrite_sql)
                logging.info(f"Updated hydrofabric geopackage at {dest_master_path} with table '{table_name}'")

    logging.info("FINISHED writing and transferring parameters to GeoPackages.")
